baseURL = "https://yourblog.azurestaticapps.net/"
languageCode = "en-us"
title = "My Side Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true
